"""
Docstring for the test module.
"""
from my_class import MyClass


def _is_ok(my_class: MyClass) -> bool:
    """
    Helper function in the test module.
    This is a private method and does not appear in the autogenerated documentation by default.

    :param my_class: An instance of `MyClass`.
    """
    return my_class.is_ok()


def test_something():
    """
    A test in the module (as opposed to in a class).
    """
    # Doesn't do anything
    assert True


class TestMyClass:
    """
    Docstring for the test class.
    """

    def test_is_ok(self):
        """
        Tests if it's ok.
        """
        assert MyClass(1, 'OK').is_ok() is True

    def test_is_not_ok(self):
        """
        Tests that it's not ok.
        """
        assert MyClass(0, 'ok').is_ok() is False
